### ISSUE TITLE
Connections are always behind nodes

### ISSUE THREAD

**Issue by philippfromme** [philippfromme/gitter#1]

**Comment by nikku** [comment]
Should become possible with custom ordering provider + https://github.com/bpmn-io/diagram-js/pull/214.

**Comment by philippfromme** [comment]
Still impossible due to https://github.com/bpmn-io/diagram-js/issues/216

**Comment by nikku** [comment]
:cry:

**Comment by philippfromme** [comment]
Fix is very simple though. 😄 I fixed it locally and it works like a charm now! 🎉
