### ISSUE TITLE
Gradients not working correctly for vertical connections

### ISSUE THREAD

**Issue by philippfromme** [philippfromme/gitter#10]
<img width="179" alt="bad" src="https://user-images.githubusercontent.com/7633572/26868545-9f7a232a-4b69-11e7-92a0-e6aa85d140a2.PNG">

**Comment by nikku** [comment]
How do you compute the gradient? Seems we'd need to take the direction of the connection into account and dynamically define these gradients: https://stackoverflow.com/questions/31261228/svg-polyline-gradient-apply-only-to-stroke.

**Comment by philippfromme** [comment]
I had it working 100% EXCEPT for the case that x or y of the waypoints are the same and the line being excactly vertical. We could give it another try.

**Comment by philippfromme** [comment]
Gradients won't be used in the near future.
