### ISSUE TITLE
Add animation for emission

### ISSUE THREAD

**Issue by philippfromme** [philippfromme/gitter#14]
![ezgif com-crop 3](https://user-images.githubusercontent.com/7633572/26930811-daa3df36-4c5e-11e7-88db-c5b2521931e6.gif)

**Comment by nikku** [comment]
3D or just regarding the animations?

**Comment by philippfromme** [comment]
I found that yesterday and was inspired. Of course in 2D but I really like the data flow simulation and would like to use that. You could also go crazy with nodes having activation functions or some just acting as repeaters. Lot's of things you could potentially do. :zap::zap::zap:
