### ISSUE TITLE
Add hot cues

### ISSUE THREAD

**Issue by nikku** [philippfromme/gitter#30]
![foo](https://user-images.githubusercontent.com/58601/30296025-11973928-9743-11e7-9f39-2f65cfb9c3dd.gif)

**Comment by nikku** [comment]
Works better with sounds enabled :poodle:.

**Comment by nikku** [comment]
Needs merge of `visual-history` branches on gitter and gitter-demo.

**Comment by philippfromme** [comment]
Merged via https://github.com/philippfromme/gitter/commit/a126ab97e7db2ed133f8795fa73098c27bc741d2

**Comment by nikku** [comment]
I like the re-design. 

Just two suggestions for improvement:

* the jump indication when clicking on a different slot seems a little bit to frequent (not smooth enough).
* start with slot 1 already being "saved"; this will allow users to jump back to zero and will already show the progress indicator right from the start
